Lottie file on disk
icapps/ios_lottie_dropper pull request #10
Opened 2017-03-30 14:24 UTC by AdamsDevelopment

- DetailViewModel, save file if available
- Internet connection checks
- Made a local list by saved files.
- Error handling when file not found

2017-04-03 09:31 UTC, doozMen requested changes
Toch opletten dat je de vraag niet omvormt naar een probleem dat je kan oplossen en zo het originele probleem niet mee oplost. Best veranderen

1. Connectivity uit de detailViewModel
2. DropboxDetail instantieren ipv een DBFile...
3. File 2 keer tonen. Eerst lokaal dan vanaf disk als er een diff is.
3. Diff maken van de file om te zien of animatie opnieuw getoond moet worden.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> -	[[self.client.filesRoutes listFolder:@""]
Dit is een oplossing maar was wel niet de vraag. De vraag was. 
1. Eerst toon je de lokale file
2. Als er verschil is met de file die van de server komt toon je de file opnieuw.
3. Als er geen verschil is toon je hem niet.

Ook connectivity geeft je geen zekerheid over een *internet* connectie. Het enige wat het zegt is dat er een netwerk is. Het kan nog steeds dat er op dat netwerk geen connectie met dropbox gemaakt kan worden.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> +    if ([connectivity IsConnectionAvailable]) {
Hier moet je checken of er een file is en die dan tonen. Dit verhelpt het op te lossen probleem niet maar bypassed het.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> +        // TODO: - Log message to user "No internet connection available"
User moet hier helemaal niks van weten. Gewoon lokale file tonen.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> +        [self fetchDropBoxFiles:done];
Ook hiervoor eerst lokale file ophalen, tegelijk de dropbox file halen.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> +- (void) fetchDropBoxFiles: (void (^)(void)) done {
🍻Goed dat je dit in een apparte functie hebt gezet.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> -	[[self.client.filesRoutes listFolder:@""]
Over stap 3 hadden jullie de discussie of dit wel nuttig was. Wel als je dit niet doet dan ziet de begruiker de animatie 2 keer. Of in het geval dat er geen eerdere lokale file is ziet hij even niets.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> +        DBFILESMetadata * file = [[DBFILESMetadata alloc]initWithName:content];
💀 Dit is zoals vermeld fout. Je moet een detailViewModel aanmaken hier onafhankelijk van DBFiles.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxDetailViewModel.h
> +#import "Connectivity.h"
Een detail moet geen kennis hebben van connectivity. Dat is de taak van de lijst. De taak van een detail is gewoon een file laden. Hij moet dus twee functies hebben 

1. Laden van lokale file
2. File refreshen/initieel laden van vanaf dropbox.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxDetailViewModel.m
> +    if ([connectivity IsConnectionAvailable]) {
Dit is dus zoals gezegd niet nodig een extra ingewikkeldheid die hier niet hoeft.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxDetailViewModel.m
> +- (void) checkIfFileExists: (NSFileManager *) fileManager done:(void (^) (void)) done {
💀 Dit is niet asynchroon en veel te moeilijk nu met een `block` gewoon een bool terug geven is voldoende in dit geval.

`isFileAvailableForFilemanager:` die een `Bool retourneerd is goed.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxDetailViewModel.m
> +        NSLog(@"No file in disk at: %@", [self.file pathLower]);
💀 In dit geval wordt done nooit aangeroepen.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxDetailViewModel.m
> +        // Delete local file when file on server not found or changed
🍺 Goeie case die je toegevoegd hebt en hier opgelost hebt.

2017-04-03 09:31 UTC, doozMen commented on LottieDropper/Dropbox/DropboxDetailViewModel.m
> +/// When internet connection is available try using pathLower if it exists.
Niet op internet connectie. File laden gewoon doen.

2017-04-03 09:31 UTC, doozMen commented on Podfile.lock
> +  - Reachability (~> 3.2)
Eigenlijk had je voor deze opdracht reachability helemaal niet nodig.

2017-04-03 09:32 UTC, doozMen commented
Je kan ook issues linknen door #10 te gebruiken.

2017-04-07 09:55 UTC, doozMen requested changes
Eerst detail aanpassen zoals besproken en dan ok.

2017-04-07 09:55 UTC, doozMen commented on LottieDropper/Dropbox/DropboxBrowserViewModel.m
> -    [self.dropboxFileCache enumerateObjectsUsingBlock:^(DBFILESMetadata * file, NSUInteger idx, BOOL *stop) {
Dit is dus wel nodig maar kan weg gewerkt worden door detail een DBFilesMetadata aan te laten maken vanaf een file naam.

2017-04-10 07:34 UTC, Periteus commented
TODO: Do not reload animation when file on server has no changes (diff)

2017-05-02 06:54 UTC, doozMen approved these changes
Goed begin maar wel nog steeds niet echt het goede offline gedrag zoals beschreven in het ticket

2017-05-02 06:54 UTC, merged